### ISSUE TITLE
Ubuntu 15.10 Error

### ISSUE THREAD

**Issue by scriptzteam** [coffeemakr/torweb#4]
root@:~/# sh prepare.sh
Running virtualenv with interpreter /usr/bin/python2
New python executable in virt/bin/python2
Not overwriting existing python script virt/bin/python (you must use virt/bin/python2)
Installing setuptools, pip...done.
Downloading/unpacking twisted (from -r requirements.txt (line 1))
  Downloading Twisted-15.5.0.tar.bz2 (3.1MB): 3.1MB downloaded
  Running setup.py (path:/tmp/pip-build-ZHIZRJ/twisted/setup.py) egg_info for package twisted

Downloading/unpacking txtorcon (from -r requirements.txt (line 2))
  Downloading txtorcon-0.14.2-py2-none-any.whl (190kB): 190kB downloaded
Downloading/unpacking autobahn[twisted](from -r requirements.txt %28line 3%29)
  Downloading autobahn-0.11.0.tar.gz (149kB): 149kB downloaded
  Running setup.py (path:/tmp/pip-build-ZHIZRJ/autobahn/setup.py) egg_info for package autobahn

```
package init file 'twisted/plugins/__init__.py' not found (or not a regular file)
```

  Installing extra requirements: 'twisted'
Downloading/unpacking selenium (from -r requirements.txt (line 4))
  Downloading selenium-2.48.0-py2-none-any.whl (872kB): 872kB downloaded
Downloading/unpacking OpenSSL (from -r requirements.txt (line 5))
  Could not find any downloads that satisfy the requirement OpenSSL (from -r requirements.txt (line 5))
Cleaning up...
No distributions at all found for OpenSSL (from -r requirements.txt (line 5))
Storing debug log for failure in /root/.pip/pip.log
npm WARN package.json torweb@0.0.0 license should be a valid SPDX license expression
bower ESUDO         Cannot be run with sudo

Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

You can however run a command with sudo using --allow-root option

root@:~/torweb# ./run.sh
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/torweb/torweb/__main__.py", line 4, in <module>
    from .server import main
  File "torweb/server.py", line 4, in <module>
    from twisted.web import server, resource, http, static, util
ImportError: No module named twisted.web

**Comment by coffeemakr** [comment]
Hi thanks for reporting. This issue should be fixed with in the lastest commits.
I removed unused packages and added the `--allow-root` option to the bower command.

**Comment by coffeemakr** [comment]
PS: I would be happy to hear if it worked!

**Comment by scriptzteam** [comment]
I also needed sudo apt-get install python-dev due to gcc ;)

installled bbbut this error now

root@:/home/torweb# ./run.sh
2015-12-20 10:29:34+0100 [-] Log opened.
2015-12-20 10:29:34+0100 [-] Site starting on 8082
2015-12-20 10:29:34+0100 [-] Starting factory <twisted.web.server.Site instance at 0x76c9a0a50e18>
2015-12-20 10:29:34+0100 [-] Connection failed: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionRefusedError'>: Connection was refused by other side: 111: Connection refused.
2015-12-20 10:29:34+0100 [-] ]
2015-12-20 10:29:34+0100 [-] Connection failed: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionRefusedError'>: Connection was refused by other side: 111: Connection refused.
2015-12-20 10:29:34+0100 [-] ]

**Comment by scriptzteam** [comment]
Updated to most recent update but still - Connection was refused by other side: 111: Connection refused.

**Comment by coffeemakr** [comment]
It seems that there is no listening process on both ports. Do you have a tor service/daemon running on your machine? You also have to enable the ControlPort in the tor configuration (torrc) and configure torweb to connect to this/these port(s).

Regards!

**Comment by coffeemakr** [comment]
PS: I've renamed the configuration file in the latest commit (fb7482f93ee8f43b4e9093baf24ac8c33c3df9c4) to torweb.json and I'll work on a better documentation.

**Comment by scriptzteam** [comment]
Using the latest update, also not works :(

netstat -tulpen
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode       PID/Program name
tcp        0      0 127.0.0.1:53            0.0.0.0:\*               LISTEN      107        1703509     24630/named
tcp        0      0 0.0.0.0:22              0.0.0.0:\*               LISTEN      0          21842       7279/sshd
tcp        0      0 127.0.0.1:953           0.0.0.0:\*               LISTEN      107        1703514     24630/named
tcp        0      0 127.0.0.1:9050          0.0.0.0:\*               LISTEN      0          130156848   14861/tor
tcp        0      0 127.0.0.1:9051          0.0.0.0:\*               LISTEN      0          130156849   14861/tor
tcp        0      0 0.0.0.0:9001            0.0.0.0:\*               LISTEN      0          130156854   14861/tor
tcp        0      0 127.0.0.1:3306          0.0.0.0:\*               LISTEN      112        2832276     20431/mysqld
tcp        0      0 127.0.0.1:6379          0.0.0.0:\*               LISTEN      109        35986       9161/redis-server 1
tcp        0      0 0.0.0.0:8333            0.0.0.0:\*               LISTEN      0          2405209     18891/bitcore
tcp6       0      0 :::80                   :::\*                    LISTEN      0          2831703     4052/apache2
tcp6       0      0 :::21                   :::\*                    LISTEN      0          129778885   15774/vsftpd
tcp6       0      0 ::1:53                  :::\*                    LISTEN      107        1703511     24630/named
tcp6       0      0 :::22                   :::\*                    LISTEN      0          21844       7279/sshd
tcp6       0      0 :::3001                 :::\*                    LISTEN      0          2409011     18891/bitcore
tcp6       0      0 ::1:953                 :::\*                    LISTEN      107        1703515     24630/named
tcp6       0      0 :::6379                 :::\*                    LISTEN      0          36137       9238/redis-server *
tcp6       0      0 :::8333                 :::\*                    LISTEN      0          2405208     18891/bitcore
udp        0      0 127.0.0.1:53            0.0.0.0:\*                           107        1703508     24630/named
udp6       0      0 ::1:53

sh run.sh
2015-12-22 10:40:58+0100 [-] Log opened.
2015-12-22 10:40:58+0100 [-] Site starting on 8082
2015-12-22 10:40:58+0100 [-] Starting factory <twisted.web.server.Site instance at 0x6e67e1a9b518>
2015-12-22 10:40:58+0100 [TorControlProtocol,client] Unhandled Error
        Traceback (most recent call last):
          File "/home/torweb/venv/local/lib/python2.7/site-packages/twisted/python/log.py", line 101, in callWithLogger
            return callWithContext({"system": lp}, func, _args, *_kw)
          File "/home/torweb/venv/local/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
            return context.call({ILogContext: newCtx}, func, _args, *_kw)
          File "/home/torweb/venv/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
            return self.currentContext().callWithContext(ctx, func, _args, *_kw)
          File "/home/torweb/venv/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
            return func(_args,_*kw)
        --- <exception caught here> ---
          File "/home/torweb/venv/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
            why = selectable.doRead()
          File "/home/torweb/venv/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 209, in doRead
            return self._dataReceived(data)
          File "/home/torweb/venv/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 215, in _dataReceived
            rval = self.protocol.dataReceived(data)
          File "/home/torweb/venv/local/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 102, in dataReceived
            return self._wrappedProtocol.dataReceived(data)
          File "/home/torweb/venv/local/lib/python2.7/site-packages/twisted/protocols/basic.py", line 454, in dataReceived
            self.lineReceived(line)
          File "/home/torweb/venv/local/lib/python2.7/site-packages/txtorcon/torcontrolprotocol.py", line 552, in lineReceived
            self.fsm.process(line)
          File "/home/torweb/venv/local/lib/python2.7/site-packages/txtorcon/spaghetti.py", line 33, in process
            next_state = self.state.process(data)
          File "/home/torweb/venv/local/lib/python2.7/site-packages/txtorcon/spaghetti.py", line 60, in process
            r = t.process(data)
          File "/home/torweb/venv/local/lib/python2.7/site-packages/txtorcon/spaghetti.py", line 125, in process
            if self.match(data):
          File "/home/torweb/venv/local/lib/python2.7/site-packages/txtorcon/spaghetti.py", line 108, in match
            return self.matcher(data)
          File "/home/torweb/venv/local/lib/python2.7/site-packages/txtorcon/torcontrolprotocol.py", line 797, in _is_multi_line
            code = int(line[:3])
        exceptions.ValueError: invalid literal for int() with base 10: 'HTT'

2015-12-22 10:40:58+0100 [-] Connection suceeded <txtorcon.torcontrolprotocol.TorControlProtocol instance at 0x6e67e1a89ef0>

**Comment by scriptzteam** [comment]
okay so changed ip to these:

{
        "connections": [
                {"host": "0.0.0.0", "port": 9051, "password": "scriptz-team"},
                {"host": "0.0.0.0", "port": 9001, "password": "scriptz-team"}
        ]
}

now sh run.sh
2015-12-22 10:43:20+0100 [-] Log opened.
2015-12-22 10:43:20+0100 [-] Site starting on 8082
2015-12-22 10:43:20+0100 [-] Starting factory <twisted.web.server.Site instance at 0x6cbe4dc83518>
2015-12-22 10:43:20+0100 [-] Connection suceeded <txtorcon.torcontrolprotocol.TorControlProtocol instance at 0x6cbe4dc71ef0>

But not working on port 8082 (listen but when i go to that port it not show nothing via firefox for example) ....

netstat -tulpen
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode       PID/Program name
tcp        0      0 127.0.0.1:8082          0.0.0.0:\*               LISTEN      0          130162898   15536/python

**Comment by coffeemakr** [comment]
Are you trying to access the webserver on localhost?

By default the server listens on 127.0.0.1 so it isn't accessible from "outside". 

You can change this (if you are really sure you want to do this ;) ) by running 

``` sh
python -m torweb --listen-address 0.0.0.0
```

instead of running `run.sh`.

However I **highly recommend not doing** this if your server is exposed to the internet.
There is no user authentication and:
- I'm almost certain that there are some security holes.
- Your tor traffic can be monitored over the web interface.

For a better security you can use a ssh tunnel with port forwarding to your own machine:

``` sh
ssh -R 8082:localhost:8082 user@example.com
```

afterwards you can access it on `localhost:8082`
See also: http://blog.trackets.com/2014/05/17/ssh-tunnel-local-and-remote-port-forwarding-explained-with-examples.html

If you're already trying to connect on localhost than this is a strange error. 

Hope I could help.
